### ISSUE TITLE
Issue with building gradle

### ISSUE THREAD

**Issue by Shono1** [MechanicalMemes/DogeCV#11]
Build Output

Information:Gradle tasks [:FtcRobotController:generateDebugSources, :FtcRobotController:generateDebugAndroidTestSources, :FtcRobotController:mockableAndroidJar, :FtcRobotController:compileDebugAndroidTestSources, :FtcRobotController:compileDebugUnitTestSources, :FtcRobotController:compileDebugSources, :TeamCode:generateDebugSources, :TeamCode:generateDebugAndroidTestSources, :TeamCode:mockableAndroidJar, :TeamCode:compileDebugAndroidTestSources, :TeamCode:compileDebugUnitTestSources, :TeamCode:compileDebugSources, :openCVLibrary3:generateDebugSources, :openCVLibrary3:generateDebugAndroidTestSources, :openCVLibrary3:mockableAndroidJar, :openCVLibrary3:compileDebugAndroidTestSources, :openCVLibrary3:compileDebugUnitTestSources, :openCVLibrary3:compileDebugSources, :DogeCV:generateDebugSources, :DogeCV:generateDebugAndroidTestSources, :DogeCV:mockableAndroidJar, :DogeCV:compileDebugAndroidTestSources, :DogeCV:compileDebugUnitTestSources, :DogeCV:compileDebugSources]
C:\Users\Sam\Desktop\Botics\DogeCV\src\main\java\com\disnodeteam\dogecv\Dogeforia.java
Error:(21, 57) error: package org.firstinspires.ftc.robotcore.external.function does not exist
Error:(22, 57) error: package org.firstinspires.ftc.robotcore.external.function does not exist
Error:(26, 66) error: package org.firstinspires.ftc.robotcore.internal.camera.libuvc.api does not exist
Error:(27, 66) error: package org.firstinspires.ftc.robotcore.internal.camera.libuvc.api does not exist
Error:(28, 66) error: package org.firstinspires.ftc.robotcore.internal.camera.libuvc.api does not exist
Error:(30, 56) error: VuforiaTrackableImpl is not public in org.firstinspires.ftc.robotcore.internal.vuforia; cannot be accessed from outside package
Error:(32, 73) error: package org.firstinspires.ftc.robotcore.internal.vuforia.externalprovider does not exist
Error:(118, 22) error: cannot find symbol method convertFrameToBitmap(Frame)
Error:Execution failed for task ':DogeCV:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED in 1s
Information:9 errors
Information:0 warnings
Information:See complete output in console

Hello!

This is my first time using Android Studio and DogeCV for FTC, so sorry if this is a PEBKAC error. I have been trying to import DogeCV/OpenCV, but whenever I try to build the app, it crashes with this output. The errors seem to be in the Dogeforia.java file. My FTC App fork can be found at https://github.com/FeehanRobotics/ftc_app.

Thank you!

**Comment by victoryforphil** [comment]
Try updating the app to 4.0 as it seems from your fork (thank you for including it) that your still running last year's sdk.

**Comment by Shono1** [comment]
Yep, that was it. Thank you!
