### ISSUE TITLE
TensorFlow (FTC Supported)

### ISSUE THREAD

**Issue by abbajabalroba** [MechanicalMemes/DogeCV#26]
Just wanted to mention that FTC now officially supports TensorFlow for vision tracking, so teams may use that since DogeCV is still in alpha.

**Comment by victoryforphil** [comment]
We are aware and have support for TF built. Just finishing polish. 

In addition the dogecv project is coming to a close so the timing works nicely. Gold Align is stable and 2018.3 will be a final and full update.

**Comment by victoryforphil** [comment]
Now team can choose what they want and pefer which is amazing. Many teams have tested both and still choose Doge for reliabity and speed. Choice is amazing and we welcome the built in TF. Plus we may release some additional models for TF and the included TF model works with doge.
