### ISSUE TITLE
How do I access the alignedX var outside of the class

### ISSUE THREAD

**Issue by GraniteBots10230** [MechanicalMemes/DogeCV#27]
I'm working on a opmode with gold align detector, and i want to use the alignedX variable in my code to use. I've messed around with some values and things but can't figure it out. More spicificly, I'm looking for the center of what the detector considers aligned.

**Comment by ovsrobotics** [comment]
Hey!
Inside the `GoldAlignDetector` class, there is two public fields: `alignPosOffset` and `alignSize`. I believe this is what you are looking for.
