### ISSUE TITLE
Documentation for Generic Detector and Color Filter API

### ISSUE THREAD

**Issue by geekkid1** [MechanicalMemes/DogeCV#6]
I would love to use your framework to make a custom Detector for a project I'm trying, but your wiki page for the Generic Detector is vague and pretty hard to understand. Can you please clarify what some of the fields do? The Color Filter API's page is easier to understand, but still leaves a little to be desired.

Can you please supply a better guide to creating customized detectors using Generic Detector and Color Filter API?

**Comment by Scroogeee** [comment]
+1 This would be really cool!

**Comment by victoryforphil** [comment]
Rewriting the docs as we speak. Going to close this issue.
